POST http://192.168.1.2:5000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "jack",
    "password": "password"
}

###

POST http://192.168.1.2:5000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "jack",
    "password": "password"
}

###

POST hhttp://192.168.1.2:5000/posts/create HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiamFjayIsInBhc3N3b3JkIjoicGFzc3dvcmQifSwiaWF0IjoxNjI5NDAxNjM2LCJleHAiOjE2Mjk0MDE2NjZ9.85H5n5pGIGmVST3mAweMRmT1P6gIKQwWYM_XYxx59Xc


###