# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
