# docker-compose.yml
version: "3"
services:
  # app:
  #   build: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://dev_user:password@postgres:5432/db
  #     NODE_ENV: development
  #     PORT: 5000
  #   ports:
  #     - "8080:8090"
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
